title: Sina Baharlouei
description: Ph.D Student, Department of Industrial and Systems Engineering, University of Southern California
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
